sound/radio/blow.wav
sound/radio/bombdef.wav
sound/radio/bombpl.wav
sound/radio/circleback.wav
sound/radio/clear.wav
sound/radio/com_followcom.wav
sound/radio/com_getinpos.wav
sound/radio/com_go.wav
sound/radio/com_reportin.wav
sound/radio/ctwin.wav
sound/radio/ct_affirm.wav
sound/radio/ct_backup.wav
sound/radio/ct_coverme.wav
sound/radio/ct_coverme2.wav
sound/radio/ct_enemys.wav
sound/radio/ct_fireinhole.wav
sound/radio/ct_fireinhole2.wav
sound/radio/ct_imhit.wav
sound/radio/ct_inpos.wav
sound/radio/ct_point.wav
sound/radio/ct_reportingin.wav
sound/radio/ct_reportingin2.wav
sound/radio/ct_reportingin3.wav
sound/radio/elim.wav
sound/radio/elim2.wav
sound/radio/enemydown.wav
sound/radio/fallback.wav
sound/radio/fallback2.wav
sound/radio/fireassis.wav
sound/radio/flankthem.wav
sound/radio/followme.wav
sound/radio/getout.wav
sound/radio/go.wav
sound/radio/go2.wav
sound/radio/hitassist.wav
sound/radio/hitassist2.wav
sound/radio/hosdown.wav
sound/radio/letsgo.wav
sound/radio/letsgo2.wav
sound/radio/letsgo3.wav
sound/radio/locknload.wav
sound/radio/matedown.wav
sound/radio/meetme.wav
sound/radio/moveout.wav
sound/radio/moveout2.wav
sound/radio/negative.wav
sound/radio/negative2.wav
sound/radio/negative3.wav
sound/radio/negative4.wav
sound/radio/negative5.wav
sound/radio/position.wav
sound/radio/regroup.wav
sound/radio/rescued.wav
sound/radio/roger.wav
sound/radio/roger2.wav
sound/radio/rounddraw.wav
sound/radio/sticktog.wav
sound/radio/stormfront.wav
sound/radio/takepoint.wav
sound/radio/terwin.wav
sound/radio/vip.wav
