//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/35hp_gladiators_day.html
halflife.wad
cs_dust.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
cs_747.wad
torntextures.wad
maps/35hp_gladiators_day.bsp
