maps/cs_51school.bsp
51school.wad
gfx/env/teatpup.tga
gfx/env/teatpdn.tga
gfx/env/teatplf.tga
gfx/env/teatprt.tga
gfx/env/teatpft.tga
gfx/env/teatpbk.tga
sound/de_torn/torn_thndrstrike.wav
sound/de_torn/torn_ambience.wav
models/medion/fac_toilet.mdl
sound/ambience/rain.wav
sound/ambience/voltage.wav
models/medion/stul.mdl
models/medion/fac_sink.mdl
models/medion/gorshok.mdl
models/medion/radiator.mdl
models/medion/51_pc.mdl
sprites/medion/med_flare.spr
models/medion/bassket_board.mdl
models/medion/bush_noleaves.mdl
models/medion/fence_med.mdl
models/medion/51_tree.mdl
models/hostage.mdl
models/pred_plant.mdl
overviews/cs_51school.txt
maps/cs_51school.res
