//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_grozniy_b1.html
gfx/env/pasmurnobk.tga
gfx/env/pasmurnodn.tga
gfx/env/pasmurnoft.tga
gfx/env/pasmurnolf.tga
gfx/env/pasmurnort.tga
gfx/env/pasmurnoup.tga
sound/ambience/wind2.wav
overviews/de_grozniy_b1.txt
overviews/de_grozniy_b1.bmp
maps/de_grozniy_b1.bsp
maps/de_grozniy_b1.txt
